import base64
import time
import datetime

from omotes_sdk.config import RabbitMQConfig
from omotes_sdk.omotes_interface import (
    OmotesInterface,
    Job,
    JobResult,
    JobProgressUpdate,
    JobStatusUpdate,
)
from omotes_sdk.workflow_type import WorkflowType, WorkflowTypeManager

rabbitmq_config = RabbitMQConfig(username="omotes", password="somepass1", virtual_host="omotes")


def handle_on_finished(job: Job, result: JobResult):
    print("--------------Logs:")
    print(result.logs)
    print()
    print("--------------ESDL:")
    print(result.output_esdl)
    print()
    print("--------------Result")
    print(
        f"Job {job.id} is done (type: {job.workflow_type.workflow_type_name}). "
        f"Status: {result.result_type}, output esdl length: {len(result.output_esdl)}, "
        f"logs length: {len(result.logs)}"
    )


def handle_on_status_update(job: Job, status_update: JobStatusUpdate):
    print(
        f"Job {job.id} progress (type: {job.workflow_type.workflow_type_name}). "
        f"Status: {status_update.status}"
    )


def handle_on_progress_update(job: Job, progress_update: JobProgressUpdate):
    print(
        f"Job {job.id} progress (type: {job.workflow_type.workflow_type_name}). Progress:"
        f" {progress_update.progress}, message: {progress_update.message}"
    )


try:
    workflow_simulator = WorkflowType("simulator", "some descr")
    workflow_manager = WorkflowTypeManager([workflow_simulator])

    omotes_if = OmotesInterface(rabbitmq_config, possible_workflows=workflow_manager)
    omotes_if.start()

    input_esdl = """PD94bWwgdmVyc2lvbj0nMS4wJyBlbmNvZGluZz0nVVRGLTgnPz4KPGVzZGw6RW5lcmd5U3lzdGVtIHhtbG5zOnhzaT0iaHR0cDovL3d3dy53My5vcmcvMjAwMS9YTUxTY2hlbWEtaW5zdGFuY2UiIHhtbG5zOmVzZGw9Imh0dHA6Ly93d3cudG5vLm5sL2VzZGwiIG5hbWU9IlVudGl0bGVkIEVuZXJneVN5c3RlbSB3aXRoIHJldHVybiBuZXR3b3JrIiBpZD0iZmRiYmY1ZWUtNmU4Ni00YzgyLTk5MjYtNGI1OWRlNDgyMzc4X3dpdGhfcmV0dXJuX25ldHdvcmsiIGRlc2NyaXB0aW9uPSIiIGVzZGxWZXJzaW9uPSJ2MjIwNyIgdmVyc2lvbj0iMSI+CiAgPGVuZXJneVN5c3RlbUluZm9ybWF0aW9uIHhzaTp0eXBlPSJlc2RsOkVuZXJneVN5c3RlbUluZm9ybWF0aW9uIiBpZD0iYzYxNWYxN2UtYzA3Ny00OGM0LThhNzgtNmFlMDVmOGE5MDhmIj4KICAgIDxjYXJyaWVycyB4c2k6dHlwZT0iZXNkbDpDYXJyaWVycyIgaWQ9ImMyNzI1OGIxLWY0ZjYtNGUwOS1hNzdhLWNlNDY2ZGJkODJkMiI+CiAgICAgIDxjYXJyaWVyIHhzaTp0eXBlPSJlc2RsOkhlYXRDb21tb2RpdHkiIGlkPSIwYmQ5Y2IwOC0yZjY5LTRlOTctOGFjOC1iZDg3YjA3ZTQ2NmEiIG5hbWU9IkhlYXRTdXBwbHkiIHN1cHBseVRlbXBlcmF0dXJlPSI4MC4wIi8+CiAgICAgIDxjYXJyaWVyIHhzaTp0eXBlPSJlc2RsOkhlYXRDb21tb2RpdHkiIGlkPSIwYmQ5Y2IwOC0yZjY5LTRlOTctOGFjOC1iZDg3YjA3ZTQ2NmFfcmV0IiByZXR1cm5UZW1wZXJhdHVyZT0iNDAuMCIgbmFtZT0iSGVhdFJldHVybiIvPgogICAgPC9jYXJyaWVycz4KICAgIDxxdWFudGl0eUFuZFVuaXRzIHhzaTp0eXBlPSJlc2RsOlF1YW50aXR5QW5kVW5pdHMiIGlkPSJmNjFhMTc5OS1iZjA0LTQxNmEtYjE1ZS05MzA5NzcyMmFkYTciPgogICAgICA8cXVhbnRpdHlBbmRVbml0IHhzaTp0eXBlPSJlc2RsOlF1YW50aXR5QW5kVW5pdFR5cGUiIGlkPSJlOTQwNWZjOC01ZTU3LTRkZjUtODU4NC00YmFiZWU3Y2RmMWIiIGRlc2NyaXB0aW9uPSJQb3dlciBpbiBNVyIgcGh5c2ljYWxRdWFudGl0eT0iUE9XRVIiIG11bHRpcGxpZXI9Ik1FR0EiIHVuaXQ9IldBVFQiLz4KICAgIDwvcXVhbnRpdHlBbmRVbml0cz4KICA8L2VuZXJneVN5c3RlbUluZm9ybWF0aW9uPgogIDxpbnN0YW5jZSB4c2k6dHlwZT0iZXNkbDpJbnN0YW5jZSIgaWQ9ImEzNTdjYmJlLWYyNzctNDJiMS04NDU2LWNiYmFkYzhjZWIyZSIgbmFtZT0iVW50aXRsZWQgSW5zdGFuY2UiPgogICAgPGFyZWEgeHNpOnR5cGU9ImVzZGw6QXJlYSIgaWQ9ImU0MDAyYzIyLWFiZDUtNDNmNi04MWE4LWU2YjVmOTYwYmZhNSIgbmFtZT0iVW50aXRsZWQgQXJlYSI+CiAgICAgIDxhc3NldCB4c2k6dHlwZT0iZXNkbDpIZWF0aW5nRGVtYW5kIiBuYW1lPSJIZWF0aW5nRGVtYW5kXzQ4ZjMiIGlkPSI0OGYzZTQyNS0yMTQzLTRkY2QtOTEwMS1jN2UyMjU1OWU4MmIiPgogICAgICAgIDxnZW9tZXRyeSB4c2k6dHlwZT0iZXNkbDpQb2ludCIgbG9uPSI0LjYzNzI2MDQzNzAxMTcyIiBsYXQ9IjUyLjE1ODc2OTYyODg2OTA0NSIgQ1JTPSJXR1M4NCIvPgogICAgICAgIDxwb3J0IHhzaTp0eXBlPSJlc2RsOkluUG9ydCIgY29ubmVjdGVkVG89IjNmMmRjMDlhLTBjZWUtNDRiZC1hMzM3LWNlYTU1NDYxYTMzNCIgaWQ9ImFmMDkwNGY3LWJhMWYtNGU3OS05MDQwLTcxZTA4MDQxNjAxYiIgY2Fycmllcj0iMGJkOWNiMDgtMmY2OS00ZTk3LThhYzgtYmQ4N2IwN2U0NjZhIiBuYW1lPSJJbiIvPgogICAgICAgIDxwb3J0IHhzaTp0eXBlPSJlc2RsOk91dFBvcnQiIGlkPSJlODkwZjY1Zi04MGU3LTQ2ZmEtOGM1Mi01Mzg1MzI0YmY2ODYiIGNvbm5lY3RlZFRvPSI0MjJjYjkyMS0yM2QyLTQ0MTAtOTA3Mi1hYWE1Nzk2YTA2MjAiIGNhcnJpZXI9IjBiZDljYjA4LTJmNjktNGU5Ny04YWM4LWJkODdiMDdlNDY2YV9yZXQiIG5hbWU9Ik91dCI+CiAgICAgICAgICA8cHJvZmlsZSB4c2k6dHlwZT0iZXNkbDpJbmZsdXhEQlByb2ZpbGUiIG11bHRpcGxpZXI9IjEuMCIgc3RhcnREYXRlPSIyMDE5LTAxLTAxVDAwOjAwOjAwLjAwMDAwMCswMDAwIiBmaWx0ZXJzPSIiIGlkPSI2MmQ3ZTJhNC05OTE5LTRmYTItOTBmNC0yOWU4ZjE4ODkxOWYiIG1lYXN1cmVtZW50PSJXYXJtaW5nVXAgZGVmYXVsdCBwcm9maWxlcyIgZGF0YWJhc2U9ImVuZXJneV9wcm9maWxlcyIgaG9zdD0icHJvZmlsZXMud2FybWluZ3VwLmluZm8iIHBvcnQ9IjQ0MyIgZmllbGQ9ImRlbWFuZDFfTVciIGVuZERhdGU9IjIwMTktMTItMzFUMjI6MDA6MDAuMDAwMDAwKzAwMDAiPgogICAgICAgICAgICA8cHJvZmlsZVF1YW50aXR5QW5kVW5pdCB4c2k6dHlwZT0iZXNkbDpRdWFudGl0eUFuZFVuaXRSZWZlcmVuY2UiIHJlZmVyZW5jZT0iZTk0MDVmYzgtNWU1Ny00ZGY1LTg1ODQtNGJhYmVlN2NkZjFiIi8+CiAgICAgICAgICA8L3Byb2ZpbGU+CiAgICAgICAgPC9wb3J0PgogICAgICA8L2Fzc2V0PgogICAgICA8YXNzZXQgeHNpOnR5cGU9ImVzZGw6R2VuZXJpY1Byb2R1Y2VyIiBwb3dlcj0iNTAwMDAwMC4wIiBuYW1lPSJHZW5lcmljUHJvZHVjZXJfY2YzZCIgaWQ9ImNmM2Q0YjVlLTQzN2YtNGMxYi1hN2Y5LTdmZDdlOGEyNjliNCI+CiAgICAgICAgPGdlb21ldHJ5IHhzaTp0eXBlPSJlc2RsOlBvaW50IiBsb249IjQuNTU4NjM5NTI2MzY3MTg4IiBsYXQ9IjUyLjE0ODg2OTM4MzQ4OTExNCIgQ1JTPSJXR1M4NCIvPgogICAgICAgIDxwb3J0IHhzaTp0eXBlPSJlc2RsOk91dFBvcnQiIGlkPSIyZDgxOGUzZC04YTM5LTRjZWMtYWZhMC1mNmRiYmZkNTA2OTYiIGNvbm5lY3RlZFRvPSJhOTc5M2E1ZS1kZjRmLTQ3OTUtODA3OS0wMTVkZmFmNTdmODIiIGNhcnJpZXI9IjBiZDljYjA4LTJmNjktNGU5Ny04YWM4LWJkODdiMDdlNDY2YSIgbmFtZT0iT3V0Ii8+CiAgICAgICAgPHBvcnQgeHNpOnR5cGU9ImVzZGw6SW5Qb3J0IiBjb25uZWN0ZWRUbz0iOTM1ZmI3MzMtOWY3Ni00YThkLTg4OTktMWFkODY4OWE0YjEyIiBpZD0iOWMyNThiOWQtMzE0OS00NzIwLTg5MzEtZjRiZWYxMDgwZWMxIiBjYXJyaWVyPSIwYmQ5Y2IwOC0yZjY5LTRlOTctOGFjOC1iZDg3YjA3ZTQ2NmFfcmV0IiBuYW1lPSJJbiIvPgogICAgICA8L2Fzc2V0PgogICAgICA8YXNzZXQgeHNpOnR5cGU9ImVzZGw6UGlwZSIgcmVsYXRlZD0iUGlwZTFfcmV0IiBuYW1lPSJQaXBlMSIgbGVuZ3RoPSI2MjY3LjAiIGlkPSJQaXBlMSIgaW5uZXJEaWFtZXRlcj0iMC41Ij4KICAgICAgICA8Z2VvbWV0cnkgeHNpOnR5cGU9ImVzZGw6TGluZSIgQ1JTPSJXR1M4NCI+CiAgICAgICAgICA8cG9pbnQgeHNpOnR5cGU9ImVzZGw6UG9pbnQiIGxvbj0iNC41NTg2Mzk1MjYzNjcxODgiIGxhdD0iNTIuMTQ4ODY5MzgzNDg5MTE0Ii8+CiAgICAgICAgICA8cG9pbnQgeHNpOnR5cGU9ImVzZGw6UG9pbnQiIGxvbj0iNC41OTQ2ODg0MTU1MjczNDUiIGxhdD0iNTIuMTY3NDA0MjE1MTQ1MjEiLz4KICAgICAgICAgIDxwb2ludCB4c2k6dHlwZT0iZXNkbDpQb2ludCIgbG9uPSI0LjYzNzI2MDQzNzAxMTcyIiBsYXQ9IjUyLjE1ODc2OTYyODg2OTA0NSIvPgogICAgICAgIDwvZ2VvbWV0cnk+CiAgICAgICAgPHBvcnQgeHNpOnR5cGU9ImVzZGw6SW5Qb3J0IiBjb25uZWN0ZWRUbz0iMmQ4MThlM2QtOGEzOS00Y2VjLWFmYTAtZjZkYmJmZDUwNjk2IiBpZD0iYTk3OTNhNWUtZGY0Zi00Nzk1LTgwNzktMDE1ZGZhZjU3ZjgyIiBjYXJyaWVyPSIwYmQ5Y2IwOC0yZjY5LTRlOTctOGFjOC1iZDg3YjA3ZTQ2NmEiIG5hbWU9IkluIi8+CiAgICAgICAgPHBvcnQgeHNpOnR5cGU9ImVzZGw6T3V0UG9ydCIgaWQ9IjNmMmRjMDlhLTBjZWUtNDRiZC1hMzM3LWNlYTU1NDYxYTMzNCIgY29ubmVjdGVkVG89ImFmMDkwNGY3LWJhMWYtNGU3OS05MDQwLTcxZTA4MDQxNjAxYiIgY2Fycmllcj0iMGJkOWNiMDgtMmY2OS00ZTk3LThhYzgtYmQ4N2IwN2U0NjZhIiBuYW1lPSJPdXQiLz4KICAgICAgPC9hc3NldD4KICAgICAgPGFzc2V0IHhzaTp0eXBlPSJlc2RsOlBpcGUiIHJlbGF0ZWQ9IlBpcGUxIiBuYW1lPSJQaXBlMV9yZXQiIGlkPSJQaXBlMV9yZXQiIGxlbmd0aD0iNjI2Ny4wIiBpbm5lckRpYW1ldGVyPSIwLjUiPgogICAgICAgIDxnZW9tZXRyeSB4c2k6dHlwZT0iZXNkbDpMaW5lIj4KICAgICAgICAgIDxwb2ludCB4c2k6dHlwZT0iZXNkbDpQb2ludCIgbG9uPSI0LjYzNjg1ODg5NjgxMzAxNyIgbGF0PSI1Mi4xNTg4NTk2Mjg5NTkwNCIgQ1JTPSJXR1M4NCIvPgogICAgICAgICAgPHBvaW50IHhzaTp0eXBlPSJlc2RsOlBvaW50IiBsb249IjQuNTk0Mjk2OTc1NDE1Mzc5NSIgbGF0PSI1Mi4xNjc0OTQyMTUyMzUyMSIgQ1JTPSJXR1M4NCIvPgogICAgICAgICAgPHBvaW50IHhzaTp0eXBlPSJlc2RsOlBvaW50IiBsb249IjQuNTU4MjI1NzA1NTY4MjM1IiBsYXQ9IjUyLjE0ODk1OTM4MzU3OTExIiBDUlM9IldHUzg0Ii8+CiAgICAgICAgPC9nZW9tZXRyeT4KICAgICAgICA8cG9ydCB4c2k6dHlwZT0iZXNkbDpJblBvcnQiIGNvbm5lY3RlZFRvPSJlODkwZjY1Zi04MGU3LTQ2ZmEtOGM1Mi01Mzg1MzI0YmY2ODYiIGlkPSI0MjJjYjkyMS0yM2QyLTQ0MTAtOTA3Mi1hYWE1Nzk2YTA2MjAiIGNhcnJpZXI9IjBiZDljYjA4LTJmNjktNGU5Ny04YWM4LWJkODdiMDdlNDY2YV9yZXQiIG5hbWU9IkluX3JldCIvPgogICAgICAgIDxwb3J0IHhzaTp0eXBlPSJlc2RsOk91dFBvcnQiIGlkPSI5MzVmYjczMy05Zjc2LTRhOGQtODg5OS0xYWQ4Njg5YTRiMTIiIGNvbm5lY3RlZFRvPSI5YzI1OGI5ZC0zMTQ5LTQ3MjAtODkzMS1mNGJlZjEwODBlYzEiIGNhcnJpZXI9IjBiZDljYjA4LTJmNjktNGU5Ny04YWM4LWJkODdiMDdlNDY2YV9yZXQiIG5hbWU9Ik91dF9yZXQiLz4KICAgICAgPC9hc3NldD4KICAgIDwvYXJlYT4KICA8L2luc3RhbmNlPgo8L2VzZGw6RW5lcmd5U3lzdGVtPgo="""

    omotes_if.submit_job(
        esdl=base64.b64decode(input_esdl).decode(),
        params_dict={
            "timestep_s": 3600,
            "start_time_unix_s": datetime.datetime(2019, 1, 2, 0, 0, 0).timestamp(),
            "end_time_unix_s": datetime.datetime(2019, 1, 2, 3, 0, 0).timestamp(),
        },
        workflow_type=workflow_simulator,
        job_timeout=None,
        callback_on_finished=handle_on_finished,
        callback_on_progress_update=handle_on_progress_update,
        callback_on_status_update=handle_on_status_update,
        auto_disconnect_on_result=True,
    )
    time.sleep(60)
finally:
    omotes_if.stop()
