services:
  rabbitmq:
    volumes:
      - "${RABBITMQ_INIT_FILE:-./rabbitmq/rabbitmq-init.sh}:/setup/rabbitmq-init.sh:ro"
    environment:
      RABBITMQ_OMOTES_USER_NAME: ${RABBITMQ_OMOTES_USER_NAME}
      RABBITMQ_OMOTES_USER_PASSWORD: ${RABBITMQ_OMOTES_USER_PASSWORD}
      RABBITMQ_CELERY_USER_NAME: ${RABBITMQ_CELERY_USER_NAME}
      RABBITMQ_CELERY_USER_PASSWORD: ${RABBITMQ_CELERY_USER_PASSWORD}

  omotes_influxdb:
    volumes:
      - "${INFLUXDB_INIT_FILE:-./influxdb/influxdb-init.sh}:/setup/influxdb-init.sh:ro"
    environment:
      INFLUXDB_WRITE_USER: ${INFLUXDB_WRITE_USER}
      INFLUXDB_WRITE_USER_PASSWORD: ${INFLUXDB_WRITE_USER_PASSWORD}
      INFLUXDB_FRONTEND_ADMIN_USER: ${INFLUXDB_FRONTEND_ADMIN_USER}
      INFLUXDB_FRONTEND_ADMIN_USER_PASSWORD: ${INFLUXDB_FRONTEND_ADMIN_USER_PASSWORD}
      INFLUXDB_PORT: ${INFLUXDB_PORT}

  orchestrator_postgres_db:
    volumes:
      - "${POSTGRES_INIT_FILE:-./postgres/postgres-init.sql}:/setup/init.sql:ro"
