services:
  system_tests:
    build: system_tests/ # This is referenced from root of repo due to how docker-compose works.
    networks:
      - omotes
    depends_on:
      rabbitmq:
        condition: service_healthy
      omotes_influxdb:
        condition: service_healthy
      orchestrator:
        condition: service_started
    environment:
      RABBITMQ_USERNAME: omotes
      RABBITMQ_PASSWORD: somepass1
      RABBITMQ_VIRTUALHOST: omotes
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672

      POSTGRES_HOST: orchestrator_postgres_db
      POSTGRES_PORT: 5432
      POSTGRES_ORCHESTRATOR_USER_NAME: omotes_orchestrator
      POSTGRES_ORCHESTRATOR_USER_PASSWORD: somepass3

      INFLUXDB_HOST: omotes_influxdb
      INFLUXDB_ADMIN_USER: root
      INFLUXDB_ADMIN_PASSWORD: 9012

  orchestrator:
    environment:
      TIMEOUT_JOB_MANAGER_START_BUFFER_SEC: 2
      TIMEOUT_JOB_HANDLER_RERUN_SEC: 5
      JOB_RETENTION_SEC: 10

  orchestrator_postgres_db:
    ports:
      - "${POSTGRES_DEV_PORT}:5432"
