[agent]
  interval = "5s"
  flush_interval = "5s"

[[inputs.docker]]
  endpoint = "unix:///var/run/docker.sock"
  source_tag = true
  container_state_include = ["running", "exited"]
  docker_label_include = ["com.docker.compose.project", "com.docker.compose.service", "io.prefect.*"]
  namepass = [
    "docker_container_mem",
    "docker_container_cpu",
    "docker_container_status",
    "docker_container_net",
  ]

[[inputs.docker]]
  alias = "docker-storage-usage"
  endpoint = "unix:///var/run/docker.sock"
  source_tag = true
  container_state_include = ["running", "exited"]
  docker_label_include = ["com.docker.compose.project", "com.docker.compose.service", "io.prefect.*"]
  storage_objects = ["container", "volume"]
  interval = "1m"
  namepass = ["docker_disk_usage"]

[[inputs.disk]]
  mount_points = ["/hostfs"]
  ignore_fs = []
  namepass = ["disk"]

[[inputs.mem]]

[[inputs.cpu]]
  percpu = false
  totalcpu = true

[[inputs.system]]
  include = ["cpus"]

[[outputs.prometheus_client]]
  listen = ":9273"
  expiration_interval = "90s"