"""add GROW_SIMULATOR option

Revision ID: 218b69952592
Revises: 67695c1cef7e
Create Date: 2023-09-25 14:05:03.691231

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '218b69952592'
down_revision: Union[str, None] = '67695c1cef7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE workflowtype RENAME VALUE 'GROWTH_OPTIMIZER' TO 'GROW_OPTIMIZER'")
    op.execute("ALTER TYPE workflowtype ADD VALUE 'GROW_SIMULATOR'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE workflowtype RENAME VALUE 'GROW_OPTIMIZER' TO 'GROWTH_OPTIMIZER'")
    # TODO: Should create new enum type so that it can be deleted and recreated

    # ### end Alembic commands ###
