#!/bin/bash
. "$(dirname "$0")"/_select_docker_compose.sh
. "$(dirname "$0")"/_load_dot_env.sh $1

# Deploy postgres omotes schema
$DOCKER_COMPOSE -f ${2} --env-file ${1} --profile=manual_dev down orchestrator_postgres_db_dev
$DOCKER_COMPOSE -f ${2} --env-file ${1} up -d --wait orchestrator_postgres_db

$DOCKER_COMPOSE -f ${2} exec orchestrator_postgres_db psql -d postgres -c 'CREATE DATABASE omotes_jobs;'

DOCKER_EXEC="$DOCKER_COMPOSE -f ${2} exec orchestrator_postgres_db psql -d omotes_jobs -c"

${DOCKER_EXEC} "CREATE USER ${POSTGRES_ORCHESTRATOR_USER_NAME} WITH PASSWORD '${POSTGRES_ORCHESTRATOR_USER_PASSWORD}';"
${DOCKER_EXEC} "ALTER USER ${POSTGRES_ORCHESTRATOR_USER_NAME} WITH PASSWORD '${POSTGRES_ORCHESTRATOR_USER_PASSWORD}';"
${DOCKER_EXEC} "GRANT ALL PRIVILEGES ON DATABASE omotes_jobs TO ${POSTGRES_ORCHESTRATOR_USER_NAME};"
${DOCKER_EXEC} "GRANT ALL PRIVILEGES ON SCHEMA public TO ${POSTGRES_ORCHESTRATOR_USER_NAME};"
${DOCKER_EXEC} "GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO ${POSTGRES_ORCHESTRATOR_USER_NAME};"
${DOCKER_EXEC} "GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO ${POSTGRES_ORCHESTRATOR_USER_NAME};"
${DOCKER_EXEC} "ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO ${POSTGRES_ORCHESTRATOR_USER_NAME};"
${DOCKER_EXEC} "ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO ${POSTGRES_ORCHESTRATOR_USER_NAME};"
