CREATE USER :PG_USERNAME WITH PASSWORD :'PG_PASSWORD';
ALTER USER :PG_USERNAME WITH PASSWORD :'PG_PASSWORD';
GRANT ALL PRIVILEGES ON DATABASE :PG_DB TO :PG_USERNAME;
GRANT ALL PRIVILEGES ON SCHEMA public TO :PG_USERNAME;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO :PG_USERNAME;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO :PG_USERNAME;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO :PG_USERNAME;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO :PG_USERNAME;
