[meta]
  dir = "/var/lib/influxdb/meta"

[data]
  dir = "/var/lib/influxdb/data"
  wal-dir = "/var/lib/influxdb/wal"
  # limits parallel compaction goroutines on startup
  max-concurrent-compactions = 1
  # caps the write cache at 1GB
  cache-max-memory-size = 1073741824

[monitor]
  store-enabled = true
  store-database = "_internal"
  store-interval = "300s"