INFLUXDB_EXEC="influx -username $INFLUXDB_ADMIN_USER -password $INFLUXDB_ADMIN_PASSWORD -host omotes_influxdb -port $INFLUXDB_PORT -execute"
$INFLUXDB_EXEC "CREATE USER $INFLUXDB_WRITE_USER WITH PASSWORD '$INFLUXDB_WRITE_USER_PASSWORD'";
$INFLUXDB_EXEC "GRANT WRITE ON omotes_timeseries TO $INFLUXDB_WRITE_USER";
$INFLUXDB_EXEC "SET PASSWORD FOR $INFLUXDB_WRITE_USER = '$INFLUXDB_WRITE_USER_PASSWORD'";
echo "Influxdb user '$INFLUXDB_WRITE_USER' created/updated.";

$INFLUXDB_EXEC "CREATE USER $INFLUXDB_FRONTEND_ADMIN_USER WITH PASSWORD '$INFLUXDB_FRONTEND_ADMIN_USER_PASSWORD' WITH ALL PRIVILEGES";
$INFLUXDB_EXEC "SET PASSWORD FOR $INFLUXDB_FRONTEND_ADMIN_USER = '$INFLUXDB_FRONTEND_ADMIN_USER_PASSWORD'";
echo "Influxdb user '$INFLUXDB_FRONTEND_ADMIN_USER' created/updated.";
